### ISSUE TITLE
Add a Code of Conduct file to the repository

### ISSUE THREAD

**Issue by rahulgithub-web** [StarmoonAI/Starmoon#11]
### Add a Code of Conduct file to the repository

**Description**  
The repository currently lacks a Code of Conduct file. This is an essential document to foster an inclusive and respectful community. Adding this file will help outline the expectations for interaction within the project and ensure a welcoming environment for contributors.

**To Reproduce**  
N/A - This issue is about the absence of a document, not a bug.

**Expected behavior**  
A `CODE_OF_CONDUCT.md` file should be added to the root of the repository, following best practices (e.g., using GitHub's Code of Conduct template or a customized version).

**Screenshots**  
N/A

**Desktop (please complete the following information):**
- OS: [e.g. Windows, macOS]
- Browser: [e.g. Chrome, Firefox]
- Version: [e.g. 100.0]

**Smartphone (please complete the following information):**
- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 15]
- Browser: [e.g. Safari]
- Version: [e.g. 15.0]

**Additional context**  
The Code of Conduct file can be generated using GitHub’s built-in feature under the "Community Standards" section of the repository settings.

**Comment by SGCODEX** [comment]
Please assign this issue to me under Hacktoberfest label sir. Thank you.

**Comment by rahulgithub-web** [comment]
@junruxiong Since I reported this issue please assign this task to me. Thank you

**Comment by rahulgithub-web** [comment]
@junruxiong it would be great if you could add the labels `hacktoberfest-accepted`, `gssoc-ext`, `hacktoberfest` with this issue.
