### ISSUE TITLE
UI Font Color Inconsistencies: Text in Chat Interface with AI is Hard to Read

### ISSUE THREAD

**Issue by Ananya54321** [StarmoonAI/Starmoon#14]
**Describe the bug**
The font color of various components in the UI is inconsistent i.e., it is white and it mixes up with the background. This can be seen in the AI chat area where it gives us a sentiment analysis of the dialogues. This is present in the privacy policy and Terms of Service as well.

**To Reproduce**
1. Log in to the website
2. Go to playground 
3. Chat with any of the personas.
or 
1. Go to website
2. Go to footer
3. Go to privacy policy and Terms of Service

**Expected behavior**
I expected to be able to see the text but I didnt know it was present until I selected it.

**Screenshots**
<img width="954" alt="Screenshot 2024-10-08 at 9 13 11 PM" src="https://github.com/user-attachments/assets/cc7ec6b8-3342-416b-9587-7d36cd06c43a">
<img width="996" alt="Screenshot 2024-10-08 at 9 13 02 PM" src="https://github.com/user-attachments/assets/445d7b88-a546-43a0-bd12-37c316205c14">
<img width="1470" alt="Screenshot 2024-10-08 at 9 23 01 PM" src="https://github.com/user-attachments/assets/092990ad-a679-47ee-92c4-dbcd4dc
<img width="1470" alt="Screenshot 2024-10-08 at 9 23 38 PM" src="https://github.com/user-attachments/assets/8c071125-2fa0-4e5f-9f6f-e5b80e4b180a">
7e311">
<img width="1470" alt="Screenshot 2024-10-08 at 9 24 03 PM" src="https://github.com/user-attachments/assets/01bee77a-8770-4173-b2e2-0e70d9142a72">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version 129.0.6668.90 (Official Build) (arm64)

**Additional context**
I am willing to submit a PR.

**Comment by akdeb** [comment]
This is now fixed. Thanks for reporting :)
