### ISSUE TITLE
Unresponsive Footer

### ISSUE THREAD

**Issue by Ananya54321** [StarmoonAI/Starmoon#15]
**Describe the bug**
The footer isn't responsive on smaller screen devices

**To Reproduce**

1. Go to Website
2. Scroll down to footer
3. If you are on a larger screen device, inspect the screen and select a smaller device

**Expected behavior**
The footer is supposed to look clean and consistent with the rest of the website.

**Screenshots**
<img width="409" alt="Screenshot 2024-10-08 at 9 29 51 PM" src="https://github.com/user-attachments/assets/1f0d9a80-74b3-4fae-ad06-56651834f28f">

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Chome
- Version 129.0.6668.90 (Official Build) (arm64)

**Smartphone (please complete the following information):**

**Additional context**
I am willing to submit a PR

**Comment by akdeb** [comment]
Closing as this is now fixed!
