### ISSUE TITLE
Update the github issue template with YML Form

### ISSUE THREAD

**Issue by utsavdotdev** [StarmoonAI/Starmoon#20]
### **Is your feature request related to a problem? Please describe.**
The current issue template is minimal and lacks structured fields, which can lead to incomplete or unclear issue reports.

### **Describe the solution you'd like**
Upgrade the existing issue template by adding a schema form that includes fields for Issue Type, Description, Steps to Reproduce, Expected Outcome, and Additional Context. This will ensure contributors provide consistent and complete information.

### **Describe alternatives you've considered**
Keeping the current minimal template, but it doesn’t adequately guide contributors to provide detailed information.

### **Additional context**
- *Before:*
<img width="985" alt="Screenshot 2024-10-09 at 7 26 03 PM" src="https://github.com/user-attachments/assets/feba2989-89bc-4b53-a0be-48601db20c13">

- *After:*
 <img width="985" alt="Screenshot 2024-10-09 at 7 02 52 PM" src="https://github.com/user-attachments/assets/f3de05cd-db3e-4266-bb7e-9da98f8e6bfc">

**Comment by junruxiong** [comment]
Hey @utsavdotdev, Thanks for your suggestion. Could you pls submit a new pull request? Thank you.

**Comment by utsavdotdev** [comment]
Ok I will proposed the PR

**Comment by utsavdotdev** [comment]
@junruxiong Just opened the PR
