### ISSUE TITLE
Want to improve UI

### ISSUE THREAD

**Issue by sanketshinde3001** [StarmoonAI/Starmoon#4]
**Describe the bug**
Fixing current UI of website.

**Screenshots**
![image](https://github.com/user-attachments/assets/874e1669-62f2-4056-a0a7-f7bc47f5d492)
Here logo not visible.
also while scrolling navbar not visible properly.

And many other UI fixes

**Desktop (please complete the following information):**

- OS: Window
- Browser - Brave

**Additional context**
I want to make PR for it.

**Comment by akdeb** [comment]
Thanks for catching @sanketshinde3001! Please submit the PR and I will review it :)

**Comment by Parth4git** [comment]
@akdeb I want to work on this issue , Please assign this issue to me.
