### ISSUE TITLE
Fixing some minor UI issues

### ISSUE THREAD

**Issue by Vaishnavi-Raykar** [StarmoonAI/Starmoon#5]
**Describe the bug**
UI is not properly shown in app.

**To Reproduce**

1. Go to '[Link](https://www.starmoon.app/onboard)'
2. Click on 'Any textbox'
3. See it

**Screenshots**
![image](https://github.com/user-attachments/assets/a3fbfabb-8b40-4313-b63b-670b3555bfa9)

**Desktop (please complete the following information):**

- OS: Windows
- Browser - Brave

**Additional context**
I want to submit PR for it.

**Comment by akdeb** [comment]
Thanks for the issue @Vaishnavi-Raykar! Your PR to fix this would be a great add. 

Currently we have tested the webapp works on 
MacOS: Chrome, Firefox, Safari
Windows: Chrome, Edge
