### ISSUE TITLE
Bug report : UI problem in the Buttons

### ISSUE THREAD

**Issue by prathamesh424** [StarmoonAI/Starmoon#6]
### Button Text are not visible properly :color of text should be white that shown in the following image 

![Screenshot 2024-10-07 101008](https://github.com/user-attachments/assets/a44dc401-550c-418d-92c5-780fc7bc8db5)
![Screenshot 2024-10-07 101029](https://github.com/user-attachments/assets/a2e93c96-9f2a-432d-b6ef-2ac6ab5e79ff)
  
### Not present the hover effect on this button
![Screenshot 2024-10-07 101049](https://github.com/user-attachments/assets/7772913a-15ce-4f32-8737-91985c039c53)

### Wrong color in hover effect .. (it should be white )
 ![Screenshot 2024-10-07 101841](https://github.com/user-attachments/assets/c2a60a50-1ced-414d-ba90-65c61a95fa8c)

### Yes ,I want to submit PR for it. 
**Assign this issue to me .**

**Comment by akdeb** [comment]
This is fixed, thanks for reporting this :)
